### ISSUE TITLE
Error Object... errors

### ISSUE THREAD

**Issue by mkell43** [Raylehnhoff/XMR-Stak-Monitor#10]
Just noticed that the error counts are off.  On my one miner, it's had 7 errors, but on the dashboard it shows it only having two.

It looks like the json from the API isn't being parsed appropriately as it only lists [object Object] when I bring up the details for the host on the dashboard.  There are two of those and I'm assuming those are the error types as this host has had 1 error of one type and 6 errors of the other.

The JSON for the error log that it's parsing:
`"error_log":[{"count":6,"last_seen":1514389514,"text":"Block expired"},{"count":1,"last_seen":1514386419,"text":"AMD Invalid Result"}]}`

**Comment by Raylehnhoff** [comment]
Yeah - I noticed this last night myself. When I was building it there were no errors so I didn't really get a chance to test it out.
